# MyBatis-Plus配置
mybatis-plus:
  # *Mapper.xml文件路径
  mapper-locations: classpath*:mapper/*.xml
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.example.**.entity
  global-config:
    db-config:
      # 全局默认主键类型
      id-type: ID_WORKER
      # 字段策略，null值的字段不会拼接到SQL中
      field-strategy: not_null
      logic-delete-field: remove_flag
      logic-delete-value: NOW()
      logic-not-delete-value: 'NULL'
  configuration:
    # DB列名到JavaBean属性名映射，符合规则无需使用@TableField注解指定数据库字段名（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    # 配置文件中的所有映射器已经配置的任何缓存
    cache-enabled: true
    # 配置JdbcTypeForNull, Oracle数据库必须配置
    jdbc-type-for-null: 'null'
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
